"""we test

Revision ID: b70a2483e2a8
Revises: 
Create Date: 2023-02-19 13:03:10.776055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b70a2483e2a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_student_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_student_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_student_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_student_email'), type_='unique')

    # ### end Alembic commands ###
